// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2vBLQDoc3RitS4H7w73NR2dwLur95M_w',
    appId: '1:703682650920:web:5094542719232454d1261d',
    messagingSenderId: '703682650920',
    projectId: 'verdant2-ecee5',
    authDomain: 'verdant2-ecee5.firebaseapp.com',
    storageBucket: 'verdant2-ecee5.firebasestorage.app',
    measurementId: 'G-BC76QHKC02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw23F5gcZilXjlNpb5e9tYcXDTrAa1wn4',
    appId: '1:703682650920:android:fd9e4756aa60102ad1261d',
    messagingSenderId: '703682650920',
    projectId: 'verdant2-ecee5',
    storageBucket: 'verdant2-ecee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJfEXrZYXz1iK9FuN4LIzDiqCKsIUI7GY',
    appId: '1:703682650920:ios:8572325c58c16f42d1261d',
    messagingSenderId: '703682650920',
    projectId: 'verdant2-ecee5',
    storageBucket: 'verdant2-ecee5.firebasestorage.app',
    iosBundleId: 'com.example.verdant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJfEXrZYXz1iK9FuN4LIzDiqCKsIUI7GY',
    appId: '1:703682650920:ios:8572325c58c16f42d1261d',
    messagingSenderId: '703682650920',
    projectId: 'verdant2-ecee5',
    storageBucket: 'verdant2-ecee5.firebasestorage.app',
    iosBundleId: 'com.example.verdant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2vBLQDoc3RitS4H7w73NR2dwLur95M_w',
    appId: '1:703682650920:web:15b3f24b71871fbad1261d',
    messagingSenderId: '703682650920',
    projectId: 'verdant2-ecee5',
    authDomain: 'verdant2-ecee5.firebaseapp.com',
    storageBucket: 'verdant2-ecee5.firebasestorage.app',
    measurementId: 'G-YY9K85P16R',
  );
}
